on: [push]
name: Check with good testdata

jobs:
  check-good-testdata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checking testdata (pass)
        uses: ./
        working-directory: .github/testdata
        with:
          args: "--exclude Bad.scala --list"
