on: [push]
name: Check with good testdata

jobs:
  check-good-testdata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checking testdata (pass)
        uses: ./
        with:
          args: "-c .github/testdata/.scalafmt.conf --exclude .github/testdata/Bad.scala --list"
