on: [push]
name: Check with good testdata

jobs:
  check-good-testdata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Checking testdata (pass)
        uses: ./
        with:
          working-directory: .github/testdata
          args: "--exclude Bad.scala --list"
